name: calorie_diff
description: Calorie Difference indicator for AppleHealth users.
publish_to: 'none'
version: 1.5.1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_code_metrics: 5.7.2
  device_check: 1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 4.0.3
  health: 6.0.0
  flutter_hooks: 0.18.6
  flutter_riverpod: 2.3.6
  hooks_riverpod: 2.3.6
  introduction_screen: 3.1.8
  shared_preferences: 2.1.0
  cupertino_icons: 1.0.5
  intl: 0.18.0
  localizely_sdk: 2.5.1
  rate_my_app: 1.1.4
  freezed: 2.3.2
  json_serializable: 6.6.1
  firebase_core: 2.10.0
  firebase_analytics: 10.2.1
  firebase_crashlytics: 3.1.1

dev_dependencies:
  build_runner: 2.3.3
  mockito: 5.4.0
  remove_from_coverage: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

dependency_overrides:
  intl: 0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/google-fonts/
cider:
  link_template:
    tag: https://github.com/RemeJuan/calorie_diff/releases/tag/%tag% # initial release link template
    diff: https://github.com/RemeJuan/calorie_diff/compare/%from%...%to% # subsequent releases link template

flutter_intl:
  enabled: true
  localizely:
    ota_enabled: true
    project_id: acdfa863-c3ee-42c6-a9e5-da9c1eee7dae
