name: calorie_diff
description: Calorie Difference indicator for AppleHealth users.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.0
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  device_check: 1.0.0
  flutter:
    sdk: flutter
  google_fonts: 4.0.3
  health: 4.5.0
  flutter_hooks: 0.18.6
  flutter_riverpod: 2.3.0
  hooks_riverpod: 2.3.0
  introduction_screen: 3.1.6
  shared_preferences: 2.0.18
  cupertino_icons: 1.0.5
  intl: 0.18.0
  rate_my_app: 1.1.3
  freezed: 2.3.2
  json_serializable: 6.6.1
  firebase_core: 2.7.0
  firebase_analytics: 10.1.4
  firebase_crashlytics: 3.0.15

dev_dependencies:
  build_runner: 2.3.3
  mockito: 5.3.2
  remove_from_coverage: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google-fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
cider:
  link_template:
    tag: https://github.com/RemeJuan/calorie_diff/releases/tag/%tag% # initial release link template
    diff: https://github.com/RemeJuan/calorie_diff/compare/%from%...%to% # subsequent releases link template