name: calorie_diff
description: Calorie Difference indicator for AppleHealth users.
publish_to: 'none'
version: 1.5.1+2
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_code_metrics: 5.7.6
  device_check: 1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 5.1.0
  health: 8.0.0
  flutter_hooks: 0.20.0
  flutter_riverpod: 2.3.7
  hooks_riverpod: 2.3.8
  introduction_screen: 3.1.11
  shared_preferences: 2.2.0
  cupertino_icons: 1.0.5
  intl: 0.18.1
  localizely_sdk: 2.5.2
  rate_my_app: 2.0.0
  freezed: 2.4.2
  json_serializable: 6.7.1
  firebase_core: 2.15.1
  firebase_analytics: 10.4.5
  firebase_crashlytics: 3.3.5

dev_dependencies:
  build_runner: 2.4.6
  mockito: 5.4.2
  remove_from_coverage: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

dependency_overrides:
  intl: 0.18.1
  analyzer: 6.2.0
  http: 1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/google-fonts/
cider:
  link_template:
    tag: https://github.com/RemeJuan/calorie_diff/releases/tag/%tag% # initial release link template
    diff: https://github.com/RemeJuan/calorie_diff/compare/%from%...%to% # subsequent releases link template

flutter_intl:
  enabled: true
  localizely:
    ota_enabled: true
    project_id: acdfa863-c3ee-42c6-a9e5-da9c1eee7dae
