name: calorie_diff
description: Calorie Difference indicator for AppleHealth users.
publish_to: 'none'
version: 1.5.2
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  device_check: 1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.0
  health: 13.1.1
  flutter_hooks: ^0.21.3
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  introduction_screen: ^3.1.17
  shared_preferences: 2.5.3
  cupertino_icons: 1.0.8
  intl: 0.20.2
  localizely_sdk: 2.7.1
  rate_my_app: ^2.3.2
  freezed: 3.2.0
  json_serializable: 6.10.0
  firebase_core: 4.0.0
  firebase_analytics: 12.0.0
  firebase_crashlytics: 5.0.0

dev_dependencies:
  build_runner: 2.7.0
  mockito: 5.5.0
  remove_from_coverage: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  frontend_server_client: 4.0.0

dependency_overrides:
  build: 3.0.2
  build_runner_core: 9.3.0
  win32: 5.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/google-fonts/
cider:
  link_template:
    tag: https://github.com/RemeJuan/calorie_diff/releases/tag/%tag% # initial release link template
    diff: https://github.com/RemeJuan/calorie_diff/compare/%from%...%to% # subsequent releases link template

flutter_intl:
  enabled: true
  localizely:
    project_id: acdfa863-c3ee-42c6-a9e5-da9c1eee7dae
