name: Flutter App Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "GMT+2"
          timezoneMacos: "GMT+2"
          timezoneWindows: "GMT+2"
  
      - name: Install Dependencies
        run: flutter packages get

      - name: Run tests
        run: flutter test test --no-pub --test-randomize-ordering-seed random --coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage/lcov.info

      - uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: './coverage/lcov.info'
          min_coverage: 75
